In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv


In [2]:
train='../input/digit-recognizer/train.csv'
test='../input/digit-recognizer/test.csv'

In [3]:
df=pd.read_csv(train)

In [4]:
len(df)

42000

In [5]:
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [7]:
X=df.drop(columns='label')
y=df['label']

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
def get_model(model,df):
    X_train,X_test,y_train,y_test= train_test_split(X,y,test_size = 0.2)
    mms = MinMaxScaler()
    X_train = mms.fit_transform(X_train)
    X_test = mms.transform(X_test)
    model.fit(X_train,y_train)
    predicted=model.predict(X_test)
    print('Accuracy : ',100*accuracy_score(y_test,predicted))
    print('F1 score:', f1_score(y_test, predicted,average='weighted'))
    print('Precision Score : ',100*precision_score(y_test,predicted,average='weighted'))
    print('Recall Score : ',100*recall_score(y_test,predicted,average='weighted'))
    print ('Confussion matrix:',confusion_matrix(y_test, predicted))

**KNN**

In [9]:
from sklearn.neighbors import KNeighborsClassifier as knc
model = knc(n_neighbors=10)
get_model(model,df)

Accuracy :  96.30952380952381
F1 score: 0.9630532863536609
Precision Score :  96.35741095960465
Recall Score :  96.30952380952381
Confussion matrix: [[822   1   0   0   0   1   3   0   0   0]
 [  0 936   2   1   2   0   0   1   0   1]
 [  6  16 764   4   0   1   0  13   2   1]
 [  1   6   6 832   0  11   1   6   6   5]
 [  1  13   0   0 774   0   1   4   0  20]
 [  2   4   1   9   2 739   8   0   0   2]
 [  7   0   0   0   0   6 821   0   0   0]
 [  2  16   2   0   1   0   0 864   0   9]
 [  2   7   2  11   2  16   5   6 717   9]
 [  3   3   1   2  12   1   2  18   1 821]]


**Random Forest**

In [10]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
get_model(model,df)

Accuracy :  96.82142857142857
F1 score: 0.9681939836165052
Precision Score :  96.81809381425022
Recall Score :  96.82142857142857
Confussion matrix: [[802   0   0   0   0   1   5   0   2   1]
 [  0 927   6   4   2   1   0   1   0   0]
 [  1   0 785   6   6   1   2  12   4   2]
 [  0   1  12 843   0  14   1   4   6   2]
 [  3   2   1   0 781   0   1   1   3  11]
 [  2   3   1  11   1 743   3   1   6   7]
 [  2   1   0   0   1   5 845   0   2   0]
 [  1   2   8   1   3   0   0 830   1  10]
 [  1   5   5   3   2   8   3   1 772   4]
 [  2   1   0  13   9   2   1   8   8 805]]


**Decision Tree Classifier**

In [11]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
get_model(model,df)

Accuracy :  85.85714285714286
F1 score: 0.8585283885026943
Precision Score :  85.8577644867283
Recall Score :  85.85714285714286
Confussion matrix: [[791   0  10  11   3   8  11   4  12   6]
 [  3 885   7   8   7   4   6   6  10   3]
 [ 12  11 697  32  13   5  12  23  19  13]
 [  5   9  27 707  12  46   6  15  21  13]
 [  4   6  18   6 652   6   7   6  18  47]
 [ 13  10   7  45   9 628  20   5  19  20]
 [  9   3  14   4  17  14 754   0  27   3]
 [  7   9  13  10   8   5   2 785   7  32]
 [  6   7  24  31  16  17  16  15 594  22]
 [  5   4  14  16  54  18   6  27  27 719]]


**K Means**

In [12]:
from sklearn.cluster import KMeans
model=KMeans(n_clusters=10)
get_model(model,df)

Accuracy :  16.380952380952383
F1 score: 0.1533258272760942
Precision Score :  14.62928085459952
Recall Score :  16.380952380952383
Confussion matrix: [[ 24   1 629   0  12  27   7   5  85   1]
 [  2   0   0 542   0   0   1 412   0   2]
 [ 27   5   9  34  23  59 560  56  29   5]
 [  4  14   4  50  11 564  36  14 187   2]
 [ 12 209   0  17 325   0   4  30   1 211]
 [ 14  28  12  16  26 245   1  96 264  53]
 [708   0   9  49  33   7  14  28  26   1]
 [  2 313   1  34  90   0   3  33   0 370]
 [  8  27   7  30  16 203   6  51 441  33]
 [  3 339   9  20 221  11   1   6   5 235]]


**Naive Bayes**

In [13]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
get_model(model,df)

Accuracy :  56.03571428571429
F1 score: 0.5168473090384101
Precision Score :  67.12241788537311
Recall Score :  56.03571428571429
Confussion matrix: [[760   2   0   2   2   3  20   0  39  11]
 [  0 891   3   5   1   1   9   2  15   9]
 [ 84  25 203  87  13   5 201   1 230   5]
 [ 43  47   3 269   2   1  47   9 346  76]
 [ 17  14   5   7 139   6  65   5 199 377]
 [ 83  28   4  13   6  36  31   1 467  64]
 [  5   9   4   1   1   3 751   0  22   0]
 [  0   6   1  13  13   2   8 307  36 494]
 [ 15 137   0  10   4   4  14   1 565 102]
 [  1   7   2   2   5   1   0   9  20 786]]


**LGBM Classifier**

In [24]:
import lightgbm as ltb
ltb = ltb.LGBMClassifier(learning_rate=0.2,max_depth=-5,random_state=1)
get_model(ltb,df)

Accuracy :  97.82142857142857
F1 score: 0.9782126079201786
Precision Score :  97.82404049409057
Recall Score :  97.82142857142857
Confussion matrix: [[786   0   1   0   0   0   1   0   5   1]
 [  0 904   2   2   0   0   1   1   3   0]
 [  1   1 820   2   4   1   1   3   3   2]
 [  2   0   7 841   0   3   0   4   3   4]
 [  2   2   0   0 798   0   1   1   1   7]
 [  2   0   1   5   1 724   3   0   2   4]
 [  1   0   1   0   1  13 792   0   2   0]
 [  0   3   8   1   2   0   0 898   0   5]
 [  0   1   3   2   2   5   2   1 812   2]
 [  2   0   2  12   8   4   0   6   4 842]]


**Support Vector Machine**

In [17]:
from sklearn.svm import SVC 
svc = SVC(kernel='poly', random_state = 1)
get_model(svc,df)

Accuracy :  97.38095238095238
F1 score: 0.9737966220736752
Precision Score :  97.38499154952419
Recall Score :  97.38095238095238
Confussion matrix: [[818   0   1   0   1   2   2   0   1   0]
 [  0 934   4   0   2   1   3   3   3   1]
 [  6   1 834   3   2   2   1   4   2   0]
 [  0   1   3 848   0  10   0   3   6   1]
 [  0   3   0   0 763   1   3   0   0   9]
 [  3   2   1   3   2 744   4   1   6   2]
 [  6   1   2   0   2   6 785   0   2   0]
 [  0  12   7   0   4   1   0 861   1   7]
 [  4   4   7   5   6   3   2   0 746   4]
 [  4   2   0   2   8   0   0   6   3 847]]


In [19]:
svc = SVC(kernel='linear', random_state = 1)
get_model(svc,df)

Accuracy :  92.58333333333333
F1 score: 0.925629319299822
Precision Score :  92.58139532430879
Recall Score :  92.58333333333333
Confussion matrix: [[791   0   6   0   2   8   9   0   3   0]
 [  0 924   3   2   0   2   0   0   8   2]
 [  3  11 757  11   6   1   5   6   9   1]
 [  6   6  18 808   2  32   1   3  11   6]
 [  2   1  10   1 716   0   4   3   2  22]
 [  9   2   9  27   8 662  12   2  15   4]
 [  7   1   8   0   9  13 829   0   4   0]
 [  2   7   6   6   8   2   0 827   5  21]
 [  7  14  11  30   5  27   3   2 723   6]
 [  6   1   7  11  32   2   0  39   5 740]]


In [30]:
sub =  pd.read_csv('../input/digit-recognizer/sample_submission.csv')

In [31]:
sub.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [33]:
sub.to_csv('Submission.csv', index = False)